### PR TITLE
removed unused xql files

### PR DESCRIPTION
**Pull request by daniel-jettka**
removed:
- getAnnotationParticipants.xql
- loginToTextGrid.xql
- checkTextGridLogin.xql
- getAnnotationsInRendering.xql

combines issues #366 #322 and #324

### CODE REVIEW

**Review by bwbohl — DISMISSED** [review]

**Review by bwbohl — APPROVED** [review]

**Review by bwbohl — DISMISSED** [review]

**Comment by bwbohl** [comment]
The branch had some merge conflicts that had to be resolved locally, so I rebased it on develop and pushed it. Unfortunately this means we need someone else to review: @Edirom/edirom-online-developer please feel free ;-)

**Comment by peterstadler** [comment]
Sorry, but the current PR looks rather polluted now with 93 commits and 50 changed files. My recommendation would be to clean this mess up and force push the branch.

**Comment by bwbohl** [comment]
sorry for that, obviously something went wrong here…

**Review by bwbohl — APPROVED** [review]

**Comment by bwbohl** [comment]
ok fixed it

**Pull request merged**
