### PR TITLE
Resolving issue #453

### PR DESCRIPTION
**Pull request by hizclick**
## Description, Context and related Issue

Resolving issue Refs #453

## How Has This Been Tested?

Tested with Klarinettenquintett

## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)
- Documentation Update
- Improvement
- Refactoring

## Overview

- I have updated the inline documentation accordingly.
- I have performed a self-review of my code, according to the [style guide](https://github.com/Edirom/Edirom-Online/blob/develop/STYLE-GUIDE.md)
- I have read the [CONTRIBUTING](https://github.com/Edirom/Edirom-Online/blob/develop/CONTRIBUTING.md) document.
- I have added tests to cover my changes at [testing](https://github.com/Edirom/Edirom-Online/tree/develop/testing)
- All new and existing tests passed.

### CODE REVIEW

**Comment by peterstadler** [comment]
Is this not the same code change as in #487 ?

**Comment by hizclick** [comment]
Yes, it is the same, thank you. IMO, the solution for both issues is also the same as   ; Ie, I will close this PR and commit the changes in PR https://github.com/Edirom/Edirom-Online/pull/487

**Comment by bwbohl** [comment]
Can the corresponding branch be deleted?

**Comment by hizclick** [comment]
@bwbohl just did

**Pull request closed without merging**
