### PR TITLE
Getting rid of Textgrid

### PR DESCRIPTION
**Pull request by DennisFriedl**
## Description, Context and related Issue
- Removed the function "eutil:getDoc" which is not necessary anymore without Textgrid
- Changed all "eutil:getDoc" calls to standard "doc" calls
- Removed Textgrid case in an OR statement

#322

## How Has This Been Tested?
Tested with the EditionExample.

## Types of changes
- Cleaning up

## Overview
- I have performed a self-review of my code, according to the [style guide](https://github.com/Edirom/Edirom-Online/blob/develop/STYLE-GUIDE.md)
- I have read the [CONTRIBUTING](https://github.com/Edirom/Edirom-Online/blob/develop/CONTRIBUTING.md) document.

### CODE REVIEW

**Comment by peterstadler** [comment]
My take on that would be a little bit different. I actually like the concept of a dedicated `eutil:getDoc` function because it provides a canonical way of getting a document  (from whatever location). Now we are removing support for TextGrid but maybe we'll add support for GitHub in the future?

Additionally, the standard `doc` function is not very robust and will fail with an error if it can't parse the resource as XML. Hence such a wrapper function is a very good place for adding proper error handling.

**Comment by DennisFriedl** [comment]
You are right. Was also thinking of keeping it but thought it would look a little sad with just a return of "doc". But with correct Error handling it gets relevant again.

**Comment by DennisFriedl** [comment]
I reverted the unwanted changes and got only rid of the textgrid part in the wrapper function. @peterstadler what would be a good way of error handling here? The calls of the function expect a document, so shouldn't "doc()" fail when it can't parse?

**Comment by peterstadler** [comment]
It's a little bit beyond the scope of #322 but I couldn't resist to provide my take on a canonical function (including tests) for loading documents within the Edirom.

**Review by peterstadler — APPROVED** [review]
tested briefly with the clarinet quintet and all seemed to work

**Pull request merged**
