### PR TITLE
Param for Imagepath

### PR DESCRIPTION
**Pull request by elena1113**
Please check and merge

### CODE REVIEW

**Comment by roewenstrunk** [comment]
The edition specific preference file is not loaded in the eutil:getPreference function. Try something like:
```xquery
declare function eutil:getPreference($key as xs:string, $edition as xs:string?) as xs:string {
     let $file := doc('../prefs/edirom-prefs.xml')
     let $projectFile := doc(edition:getPreferencesURI($edition))
     return    
        if($projectFile != null) then ($projectFile//entry[@key = $key]/string(@value))
        else ($file//entry[@key = $key]/string(@value))   
};
```
and pass the `edition` parameter to the function

**Comment by roewenstrunk** [comment]
Reopening the pull request

**Comment by bwbohl** [comment]
This still open?
As we decided for gitflow PRs should not be issued against master but develop instead!
This brings up the issue to make develop the default branch #57

**Comment by bwbohl** [comment]
I tested this locally and the new imagePathParam works great!

**Comment by nikobeer** [comment]
Tested… works!

**Comment by nikobeer** [comment]
See #62. This could be closed.

**Comment by nikobeer** [comment]
closed.

**Pull request closed without merging**
