### PR TITLE
add code of conduct

### PR DESCRIPTION
**Pull request by krHERO**
this PR adds a code of conduct file to the edirom-online repository

Refs #403

### CODE REVIEW

**Review by bwbohl — APPROVED** [review]
As this code of conduct speaks of community leaders we probably should clearly articulate who such a leader is?

**Comment by krHERO** [comment]
> As this code of conduct speaks of community leaders we probably should clearly articulate who such a leader is?

thanks for the review and your request. i suggest to talk about that at the next community meeting 4.9.2024.

**Review by daniel-jettka — APPROVED** [review]
Looks good, Thank you.

**Comment by krHERO** [comment]
> > As this code of conduct speaks of community leaders we probably should clearly articulate who such a leader is?
> 
> thanks for the review and your request. i suggest to talk about that at the next community meeting 4.9.2024.

we tried to figure out, if and how a pre-defined group of edirom developers in github could be linked, but failed. 
we want to replace the term "leader" with the group of the current edirom developer team (and planned to ideally set a link to this team), but without writing single names of persons. 
regarding [github docs on team visibility](https://docs.github.com/en/organizations/organizing-members-into-teams/about-teams#team-visibility) that seems to be impossible: "People who are not members of the organization cannot view any teams"

I suggest to use the term "edirom developers" to replace it with leaders (the info-mail address is already placed). all current developers are following the code of conduct so far and are able to monitor it and i assume we would not accept future edirom developers, that are not following the rules of the code of conduct. so we should be prepared well enough with responsible persons if something is happening from the outside regarding comments on issues etc. 

any thoughts or alternatives about this suggestion?

**Pull request merged**
