### PR TITLE
156 searchwindow use edition path for collection function

### PR DESCRIPTION
**Pull request by hizclick**
## Description, Context and related Issue

Refs #

## Types of changes

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- I have updated the documentation accordingly.
- All new and existing tests passed.

### CODE REVIEW

**Comment by peterstadler** [comment]
This still needs some work. There's inline function documentation missing and the kwic results are not output properly, i.e. only the search terms without context.
Additionally, the text input in the upper right does not trigger a search but only opens the search window. That should be fixed, too.

I will look into these issues.

**Comment by peterstadler** [comment]
I think I fixed the remaining points (function documentation, KWIC, top bar text input).

There's yet another thing, i.e. the CSS styling which seems to be missing. Neither the KWIC display seems adequate nor are the search terms highlighted in the text (although the className `searchResult` is injected correctly). This seems related to #451 so I wonder if @bwbohl can reproduce the issue here?

Some Screenshots to illustrate the CSS issue: 

Bildschirmfoto 2024-11-08 um 16 25 31
Bildschirmfoto 2024-11-08 um 16 26 51

**Comment by peterstadler** [comment]
pinging @roewenstrunk and @bwbohl  to review

**Review by roewenstrunk — APPROVED** [review]
Tested with Klarinettenquintett

**Pull request merged**
