### PR TITLE
Fix tei footnotes

### PR DESCRIPTION
**Pull request by bwbohl**
* reconceptualise transformation of TEI texts to HTML by relying primarily on TEI Stylesheets and extracting from the resulting HTML
* fix some CSS and SCSS conflicts

### CODE REVIEW

**Comment by bwbohl** [comment]
open issues:

- [ ]  footnote heading
- [ ] footnote links and backlinks

**Review by riedde — COMMENTED** [review]
Reviewed and seems to be okay. Thank you for your work! I'll test this and then approve my review.

**Comment by riedde** [comment]
@bwbohl the footnote links and backlinks are working. When backlinking the target is a bit out of the window so a bit padding would be nice, but from my view it works!

**Comment by bwbohl** [comment]
I think we can live with this for the moment ;-)

**Pull request merged**
