### PR TITLE
Feature: zenmem backend

### PR DESCRIPTION
**Pull request by bwbohl**

### CODE REVIEW

**Comment by bwbohl** [comment]
@roewenstrunk, what’s the status of this?
Is the ZenMEM backend in a state that could be used?
Aside from the answers to the above questions, this draft might include some valuable code addition, right?

**Comment by bwbohl** [comment]
ping @roewenstrunk

**Comment by roewenstrunk** [comment]
Hi @bwbohl, this needs some investigation

**Comment by bwbohl** [comment]
ping @roewenstrunk

**Comment by bwbohl** [comment]
Last call before closing in mid-November.

**Comment by roewenstrunk** [comment]
This is not helpful any more. Closing this.

**Pull request closed without merging**
