### PR TITLE
Release 1.0.0-alpha to develop

### LINKED ISSUE #125: install directory mismatch
The install directory of Edirom Online currently is `/db/apps/EdiromOnline` the setPermissions.xql uses a different path though…

https://github.com/Edirom/Edirom-Online/blob/56d0f0ebdf033924bf91351d391a1da4c3d9908b/add/setPermissions.xql#L48

What is the intended path? It should either be changed in setPermissions.xql or:

https://github.com/Edirom/Edirom-Online/blob/56d0f0ebdf033924bf91351d391a1da4c3d9908b/add/repo.xml#L10

### LINKED ISSUE #139: getAnnotationInfos.xql doomed to fail
as getAnnotationInfos.xql is called without an edition url-param retrieving category and priority names from the 'edition_path' is doomed to fail.

Or am I missing something?

### LINKED ISSUE #188: replace util:serialize with fn:serialize globally
e.g. getAnnotationsOnPage.xql fails as util:serialize is no longer defined

### LINKED ISSUE #196: show measures in measureBasedView
measureBased view show measure numbers fails

### PR DESCRIPTION
**Pull request by bwbohl**
closes #139 
closes #125
closes #183 
closes #187
closes #188 
closes #192
closes  #196

### CODE REVIEW

**Comment by bwbohl** [comment]
@riedde @roewenstrunk please test with your local testsets I already discovered some issues:

- [ ] text view no scrolling available

**Comment by bwbohl** [comment]
> * [ ]  text view no scrolling available

at the moment I haven't found why this is lost, if you spot anything, please report

**Comment by riedde** [comment]
I get some violations. (scrolling, leaflet.js; 'mousewheel', non-passive listener in app.ja, 'setTimeout' handler; )
Things that work with the edition example but not with the lehar testset (two different works).
- [ ] Concordance navigator (has no effect to the sources), work switching is okay
- [ ] Annotation Source view (no pics)
- [ ] Annotation open all sources (does maximize the annotation window, nothing else)
- [ ] Switching works (see #197) (fixed in #198)
- [ ] Source view is working, but the console reports: `GET about:blank net::ERR_UNKNOWN_URL_SCHEME` maybe caused by #197 (I have tested the release containing the fix of this issue)

**Comment by bwbohl** [comment]
closes #201

**Comment by bwbohl** [comment]
closed with [d4cbf48](https://github.com/Edirom/Edirom-Online/commit/d4cbf48c5aa266dd80434c15d6f820fd7d1eb0bc)

**Pull request closed without merging**
