### PR TITLE
Fix/splitted measures in parts

### PR DESCRIPTION
**Pull request by roewenstrunk**
Splitted measures in scores and parts should work now. Needs testing.

### CODE REVIEW

**Comment by bwbohl** [comment]
Many thx for submitting this PR. Will check it ASAP

**Comment by bwbohl** [comment]
everything works as expected only that sometimes with parts and horizontal measureViewers the zoom level is not being adjusted properly

**Review by bwbohl — APPROVED** [review]

**Comment by riedde** [comment]
closes #256

**Review by riedde — APPROVED** [review]
Thank you for this new feature :) It works also on my infrastructure.

**Pull request merged**
