### PR TITLE
Update getExtendedStaff.xql to fix loading verovio resources

### LINKED ISSUE #243: RenderingView fails depending on EXIST_DEFAULT_APP and EXIST_CONTEXT
Depending on EXIST_DEFAULT_APP and EXIST_CONTEXT the RenderingView fails due to availability of resources, e.g. when Edirom-Online is default app and context is `/exist`. Probably due to

https://github.com/Edirom/Edirom-Online/blob/c11fc78bfb8d0575d7cc12431bdade5735fefbe6/add/data/xql/getExtendedStaff.xql#L29

and 
https://github.com/Edirom/Edirom-Online/blob/c11fc78bfb8d0575d7cc12431bdade5735fefbe6/add/data/xql/getExtendedStaff.xql#L17

### PR DESCRIPTION
**Pull request by bwbohl**
* fix context for loading verovio resources

closes #243

### CODE REVIEW

**Review by riedde — COMMENTED** [review]
I had problemes changing the  exist context path on my local machine, so I couldn't get it work, but the console errors in chrome told me that the Edirom is searching the resources at the right place. Maybe @peterstadler could have a short look and merge it afterwards.

**Comment by peterstadler** [comment]
Just updated the PR by rewriting `eutil:get-app-base-url` to properly compute the app base path as seen from a client. This should work for any `EXIST_CONTEXT_PATH` without going through the REST interface.

**Comment by peterstadler** [comment]
Since this is quite a change I'm assigning this to @roewenstrunk now :)

**Comment by riedde** [comment]
Tested with modified context variable

**Pull request merged**
